'use client';
import Link from 'next/link';
import { Heart, Plus, Minus, Star, ArrowRight, ShoppingBag, X } from 'lucide-react';
import { products, getProduct, money, type Product } from '@/lib/catalog';
import { useStore } from './store-provider';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription, EmptyContent, EmptyMedia } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';
export function Stars({rating=4.8,count}:{rating?:number;count?:number}){return <span className="stars" aria-label={`${rating} out of 5 stars${count?`, ${count} sample ratings`:''}`}><span aria-hidden="true">{Array.from({length:5},(_,i)=><Star key={i} size={12} fill={i<Math.round(rating)?'currentColor':'none'}/>)}</span><b>{rating}</b>{count!==undefined&&<small>({count})</small>}</span>}
export function ProductCard({product:p}:{product:Product}){const{data,save,add,busy,loading}=useStore();return <article className="product-card"><div className="product-image"><Link href={'/product/'+p.id}><img src={p.image} alt={`${p.brand} ${p.name}, ${p.size}`} width={440} height={440} loading="lazy"/></Link>{p.badge&&<span className={'product-badge '+(!p.stock?'sold':'')}>{p.badge}</span>}<button className={'wish-button '+(data.wishlist.includes(p.id)?'saved':'')} onClick={()=>save(p.id)} disabled={busy||loading} aria-label={`${data.wishlist.includes(p.id)?'Remove from':'Save to'} wishlist: ${p.name}`} aria-pressed={data.wishlist.includes(p.id)}><Heart size={18} fill={data.wishlist.includes(p.id)?'currentColor':'none'}/></button></div><div className="product-content"><span className="product-brand">{p.brand}</span><Link href={'/product/'+p.id} className="product-name">{p.name}</Link><span className="product-size">{p.size}</span><Stars rating={p.rating} count={p.reviews}/><div className="product-bottom"><div><strong>{money(p.price)}</strong>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><button onClick={()=>add(p.id)} className="quick-add" disabled={!p.stock||busy||loading} aria-label={p.stock?`Add ${p.name} to bag`:`${p.name} is out of stock`}><Plus size={20}/></button></div></div></article>}
export function ProductGrid({items=products,mode='grid'}:{items?:Product[];mode?:string}){return <div className={'product-grid '+(mode==='list'?'list-mode':'')}>{items.map(p=><ProductCard key={p.id} product={p}/>)}</div>}
export function ProductSection({title,eyebrow,items,href='/shop'}:{title:string;eyebrow:string;items:Product[];href?:string}){return <section className="section wrap"><div className="section-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><Link className="text-link" href={href}>Shop the collection <ArrowRight size={17}/></Link></div><ProductGrid items={items}/></section>}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav aria-label="Breadcrumb" className="breadcrumbs"><Link href="/">Home</Link>{items.map((item,i)=><span key={i}><span aria-hidden="true">/</span>{item.href?<Link href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</span>)}</nav>}
export function Quantity({value,onChange,max=10,disabled=false}:{value:number;onChange:(n:number)=>void;max?:number;disabled?:boolean}){return <div className="quantity"><button aria-label="Decrease quantity" disabled={disabled||value<=1} onClick={()=>onChange(value-1)}><Minus size={15}/></button><output aria-label="Quantity">{value}</output><button aria-label="Increase quantity" disabled={disabled||value>=max} onClick={()=>onChange(value+1)}><Plus size={15}/></button></div>}
export function EmptyState({title,description,href='/shop',label='Explore wellness'}:{title:string;description:string;href?:string;label?:string}){return <Empty className="empty-state"><EmptyHeader><EmptyMedia variant="icon"><ShoppingBag/></EmptyMedia><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></EmptyHeader><EmptyContent><Link className="button" href={href}>{label}<ArrowRight size={16}/></Link></EmptyContent></Empty>}
export function StoreLoading(){return <div aria-label="Loading your saved items" role="status" className="loading-cards">{[1,2,3].map(i=><div key={i}><Skeleton className="h-32 w-full rounded-xl"/><Skeleton className="h-5 w-2/3 mt-5"/></div>)}</div>}
export function CartLines({compact=false}:{compact?:boolean}){const{data,change,busy}=useStore();return <div className={'cart-lines '+(compact?'compact':'')}>{data.cart.map(item=>{const p=getProduct(item.productId);if(!p)return null;return <div className="cart-line" key={p.id}><Link href={'/product/'+p.id}><img src={p.image} alt={p.name} width={110} height={120}/></Link><div><span className="product-brand">{p.brand}</span><Link href={'/product/'+p.id}><h3>{p.name}</h3></Link><span className="product-size">{p.size}</span><Quantity value={item.quantity} max={Math.min(10,p.stock)} disabled={busy} onChange={quantity=>change({action:'cart',productId:p.id,quantity})}/></div><div className="cart-line-end"><button aria-label={`Remove ${p.name} from bag`} disabled={busy} onClick={()=>change({action:'cart',productId:p.id,quantity:0})}><X size={17}/></button><strong>{money(p.price*item.quantity)}</strong></div></div>})}</div>}
export function SavedProducts({recent=false}:{recent?:boolean}){const{data}=useStore();const ids=recent?data.recent:data.wishlist;const items=ids.map(getProduct).filter((p):p is Product=>!!p);if(!items.length)return null;return <ProductSection title={recent?'Worth another look.':'A few of your favourites.'} eyebrow={recent?'RECENTLY VIEWED':'YOUR WISHLIST'} items={items.slice(0,4)} href={recent?'/shop':'/wishlist'}/>}
