import { database } from '@/db';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { calculateTotals, districts, getProduct, type CartItem, type Address } from '@/lib/catalog';
import { z } from 'zod';
const addressSchema=z.object({name:z.string().trim().min(2).max(120),email:z.string().email().max(200),phone:z.string().regex(/^(?:\+94|0)[0-9\s-]{9,13}$/),address:z.string().trim().min(5).max(300),city:z.string().trim().min(2).max(100),district:z.enum(districts as [string,...string[]]),postcode:z.string().regex(/^\d{5}$/)});
async function identity(request:Request){const user=await getChatGPTUser();const cookie=request.headers.get('cookie')?.match(/(?:^|;\s*)gm_guest=([a-f0-9-]{36})(?:;|$)/)?.[1];const guest=cookie??crypto.randomUUID();return {user,owner:user?'user:'+user.userId:'guest:'+guest,cookie:cookie?null:'gm_guest='+guest+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=31536000'+(new URL(request.url).protocol==='https:'?'; Secure':''),guest};}
async function claimGuest(owner:string,guest:string){if(!owner.startsWith('user:'))return;const db=database();const previous='guest:'+guest;await db.batch([db.prepare('INSERT INTO cart (owner, product_id, quantity) SELECT ?, product_id, quantity FROM cart WHERE owner = ? ON CONFLICT(owner, product_id) DO UPDATE SET quantity = MIN(10, MAX(cart.quantity, excluded.quantity))').bind(owner,previous),db.prepare('INSERT OR IGNORE INTO wishlist (owner, product_id) SELECT ?, product_id FROM wishlist WHERE owner = ?').bind(owner,previous),db.prepare('INSERT OR IGNORE INTO recently_viewed (owner, product_id, viewed_at) SELECT ?, product_id, viewed_at FROM recently_viewed WHERE owner = ?').bind(owner,previous),db.prepare('UPDATE orders SET owner = ? WHERE owner = ?').bind(owner,previous),db.prepare('DELETE FROM cart WHERE owner = ?').bind(previous),db.prepare('DELETE FROM wishlist WHERE owner = ?').bind(previous),db.prepare('DELETE FROM recently_viewed WHERE owner = ?').bind(previous)]);}
function reply(data:unknown,status=200,cookie:string|null=null){return Response.json(data,{status,headers:{'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}});}
async function readState(owner:string,user:Awaited<ReturnType<typeof getChatGPTUser>>){const db=database();const results=await db.batch<Record<string,unknown>>([db.prepare('SELECT product_id AS productId, quantity FROM cart WHERE owner = ?').bind(owner),db.prepare('SELECT product_id FROM wishlist WHERE owner = ?').bind(owner),db.prepare('SELECT product_id FROM recently_viewed WHERE owner = ? ORDER BY viewed_at DESC LIMIT 8').bind(owner),db.prepare('SELECT data FROM orders WHERE owner = ? ORDER BY created_at DESC LIMIT 50').bind(owner),db.prepare('SELECT data FROM profiles WHERE owner = ?').bind(owner)]);return {cart:results[0].results,wishlist:results[1].results.map(r=>r.product_id),recent:results[2].results.map(r=>r.product_id),orders:results[3].results.map(r=>JSON.parse(r.data as string)),profile:results[4].results[0]?JSON.parse(results[4].results[0].data as string):{},user:user?{name:user.fullName??'Wellness explorer',email:user.email}:null};}
export async function GET(request:Request){try{const id=await identity(request);if(id.user)await claimGuest(id.owner,id.guest);const product=new URL(request.url).searchParams.get('reviews');if(product){const data=await database().prepare('SELECT id, name, rating, body, created_at FROM reviews WHERE product_id = ? ORDER BY created_at DESC LIMIT 50').bind(product).all();return reply(data.results,200,id.cookie);}return reply(await readState(id.owner,id.user),200,id.cookie);}catch(error){console.error('Store read failed',error);return reply({error:'We couldn’t load your saved items. Please try again.'},503);}}
export async function POST(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin){await request.text();return reply({error:'Invalid request origin.'},403);}try{const id=await identity(request);const db=database();const data=await request.json() as Record<string,unknown>;const action=data.action;
if(action==='cart'){const product=getProduct(String(data.productId));const quantity=z.number().int().min(0).max(10).parse(data.quantity);if(!product||quantity>product.stock)return reply({error:'This quantity is no longer available.'},400,id.cookie);if(quantity===0)await db.prepare('DELETE FROM cart WHERE owner = ? AND product_id = ?').bind(id.owner,product.id).run();else await db.prepare('INSERT INTO cart (owner, product_id, quantity) VALUES (?, ?, ?) ON CONFLICT(owner, product_id) DO UPDATE SET quantity = excluded.quantity').bind(id.owner,product.id,quantity).run();}
else if(action==='wishlist'){const product=getProduct(String(data.productId));if(!product)return reply({error:'Product not found.'},404,id.cookie);if(data.saved===true)await db.prepare('INSERT OR IGNORE INTO wishlist (owner, product_id) VALUES (?, ?)').bind(id.owner,product.id).run();else await db.prepare('DELETE FROM wishlist WHERE owner = ? AND product_id = ?').bind(id.owner,product.id).run();}
else if(action==='view'){if(getProduct(String(data.productId)))await db.prepare('INSERT INTO recently_viewed (owner, product_id, viewed_at) VALUES (?, ?, ?) ON CONFLICT(owner, product_id) DO UPDATE SET viewed_at = excluded.viewed_at').bind(id.owner,String(data.productId),new Date().toISOString()).run();}
else if(action==='profile'){if(!id.user)return reply({error:'Please sign in to save your details.'},401,id.cookie);const address=addressSchema.parse(data.address);await db.prepare('INSERT INTO profiles (owner, data) VALUES (?, ?) ON CONFLICT(owner) DO UPDATE SET data = excluded.data').bind(id.owner,JSON.stringify(address)).run();}
else if(action==='order'){const orderId=z.string().uuid().parse(data.orderId);const existing=await db.prepare('SELECT data FROM orders WHERE id = ? AND owner = ?').bind(orderId,id.owner).first<{data:string}>();if(existing)return reply({order:JSON.parse(existing.data),state:await readState(id.owner,id.user)},200,id.cookie);const address=addressSchema.parse(data.address);const method=z.enum(['standard','express']).parse(data.method);if(method==='express'&&!['Colombo','Gampaha','Kalutara'].includes(address.district))return reply({error:'Express delivery is available in Colombo, Gampaha and Kalutara. Please choose standard delivery.'},400,id.cookie);const coupon=z.string().max(30).parse(data.coupon??'');if(coupon&&coupon.toUpperCase()!=='WELL10')return reply({error:'That offer code is not valid.'},400,id.cookie);const rows=await db.prepare('SELECT product_id AS productId, quantity FROM cart WHERE owner = ?').bind(id.owner).all<CartItem>();if(!rows.results.length)return reply({error:'Your bag is empty.'},400,id.cookie);for(const item of rows.results){const p=getProduct(item.productId);if(!p||p.stock<item.quantity)return reply({error:'An item in your bag is no longer available.'},400,id.cookie);}const totals=calculateTotals(rows.results,coupon,method);const now=new Date().toISOString();const order={id:orderId,created_at:now,items:rows.results.map(item=>({...item,name:getProduct(item.productId)!.name,price:getProduct(item.productId)!.price})),...totals,address:address as Address,method,status:'Sample order saved'};await db.batch([db.prepare('INSERT INTO orders (id, owner, created_at, data) VALUES (?, ?, ?, ?)').bind(orderId,id.owner,now,JSON.stringify(order)),db.prepare('DELETE FROM cart WHERE owner = ?').bind(id.owner)]);return reply({order,state:await readState(id.owner,id.user)},200,id.cookie);}
else if(action==='review'){if(!id.user)return reply({error:'Please sign in to leave a review.'},401,id.cookie);const body=z.string().trim().min(10).max(2000).parse(data.body);const rating=z.number().int().min(1).max(5).parse(data.rating);const productId=String(data.productId);if(!getProduct(productId))return reply({error:'Product not found.'},404,id.cookie);await db.prepare('INSERT INTO reviews (id, owner, product_id, name, rating, body, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)').bind(crypto.randomUUID(),id.owner,productId,id.user.fullName??'GlobalMart customer',rating,body,new Date().toISOString()).run();return reply({success:true},200,id.cookie);}
else if(action==='contact'||action==='newsletter'){const email=z.string().email().max(200).parse(data.email);const payload=action==='contact'?z.object({name:z.string().trim().min(2).max(120),message:z.string().trim().min(10).max(4000)}).parse(data):{};await db.prepare('INSERT INTO enquiries (id, kind, email, data, created_at) VALUES (?, ?, ?, ?, ?)').bind(crypto.randomUUID(),action,email,JSON.stringify(payload),new Date().toISOString()).run();return reply({success:true},200,id.cookie);}
else return reply({error:'Unknown action.'},400,id.cookie);
return reply(await readState(id.owner,id.user),200,id.cookie);
}catch(error){if(error instanceof z.ZodError)return reply({error:'Please check the details you entered.',fields:error.flatten()},400);console.error('Store save failed',error);return reply({error:'We couldn’t save that change. Your details are still here; please try again.'},503);}}
