export type Product = { id:string; name:string; brand:string; category:string; form:string; size:string; price:number; oldPrice?:number; rating:number; reviews:number; stock:number; badge?:string; image:string; description:string; source:string };
export const categories=[{id:'daily-essentials',name:'Daily essentials',short:'Daily',description:'Simple additions to your everyday routine.',color:'peach'},{id:'immunity',name:'Immune support',short:'Immunity',description:'Explore vitamin C, zinc and everyday essentials.',color:'green'},{id:'beauty',name:'Beauty from within',short:'Beauty',description:'Make a little room for your self-care ritual.',color:'blush'},{id:'digestion',name:'Gut & digestion',short:'Digestion',description:'Discover probiotics and digestive wellness.',color:'yellow'},{id:'sleep',name:'Rest & recharge',short:'Rest',description:'Create a more considered evening routine.',color:'lavender'},{id:'kids',name:'Kids & family',short:'Family',description:'Thoughtful choices for the whole household.',color:'blue'},{id:'womens-health',name:'Women’s health',short:'Women',description:'Wellness through every chapter.',color:'blush'},{id:'heart-health',name:'Heart & movement',short:'Movement',description:'Explore omega-3 and active-living essentials.',color:'green'}];
export const brands=['Nature’s Way','Blackmores','Healthy Care','Wagner','VOOST'];
export const products:Product[]=[
{id:'adult-vita-gummies',name:'Adult Vita Gummies Multivitamin',brand:'Nature’s Way',category:'daily-essentials',form:'Gummies',size:'120 pastilles',price:6450,oldPrice:7200,rating:4.8,reviews:124,stock:24,badge:'Bestseller',image:'/images/products/adult-vita-gummies.webp',description:'A convenient gummy format to complement a balanced daily routine. Check the manufacturer’s label for ingredients and suitability.',source:'https://www.naturesway.com.au/nature-s-way-adult-vita-gummies-multivitamin-120-s'},
{id:'fish-oil',name:'Fish Oil 1000',brand:'Blackmores',category:'heart-health',form:'Capsules',size:'400 capsules',price:8900,oldPrice:9900,rating:4.9,reviews:86,stock:18,badge:'Everyday favourite',image:'/images/products/fish-oil.webp',description:'An omega-3 fish oil in a soft capsule format. Explore the original manufacturer’s information before choosing your supplement.',source:'https://www.blackmores.com.au/products/fish-oil-1000'},
{id:'vitamin-c',name:'Vitamin C Blood Orange',brand:'VOOST',category:'immunity',form:'Effervescent',size:'20 tablets',price:2950,oldPrice:3450,rating:4.7,reviews:64,stock:30,badge:'Save 15%',image:'/images/products/vitamin-c.webp',description:'An effervescent addition to your daily routine. Dissolve according to the product label and check the full ingredient list.',source:'https://voostvitamins.com.au/products/effervescents/vitamin-c'},
{id:'magnesium',name:'Magnesium',brand:'Blackmores',category:'sleep',form:'Tablets',size:'100 tablets',price:4850,rating:4.8,reviews:52,stock:16,image:'/images/products/magnesium.webp',description:'A magnesium supplement in a tablet format. Read the original product information for directions and suitability.',source:'https://www.blackmores.com.au/products/magnesium'},
{id:'probiotic',name:'Restore Probiotic 50 Billion',brand:'Nature’s Way',category:'digestion',form:'Capsules',size:'30 capsules',price:6950,oldPrice:7800,rating:4.6,reviews:43,stock:12,image:'/images/products/probiotic.webp',description:'A probiotic option for your wellness shelf. Refer to the product’s label for strains, storage instructions and suitability.',source:'https://www.naturesway.com.au/nature-s-way-restore-probiotic-50-billion-30-capsules'},
{id:'collagen',name:'Beauty Collagen',brand:'Healthy Care',category:'beauty',form:'Tablets',size:'60 tablets',price:7950,rating:4.7,reviews:72,stock:8,badge:'Only 8 left',image:'/images/products/collagen.webp',description:'An addition to your beauty-from-within routine. Check the manufacturer’s ingredient list and directions before use.',source:'https://healthycare.com.au/products/healthy-care-beauty-collagen-60-tablets'},
{id:'kids-multi',name:'Kids Smart Vita Gummies Multi-Vitamin Plus',brand:'Nature’s Way',category:'kids',form:'Gummies',size:'120 pastilles',price:4350,rating:4.8,reviews:95,stock:20,image:'/images/products/kids-multi.webp',description:'A family wellness option. Always follow the age guidance on the original label and keep supplements out of reach of children.',source:'https://www.naturesway.com.au/nature-s-way-kids-smart-vita-gummies-multi-vitamin-vegies-120-s'},
{id:'womens-multi',name:'Multivitamins for Women',brand:'Blackmores',category:'womens-health',form:'Tablets',size:'60 tablets',price:7450,oldPrice:8450,rating:4.8,reviews:59,stock:0,badge:'Back soon',image:'/images/products/womens-multi.webp',description:'A multivitamin designed for women. Check the product label and ask a healthcare professional about individual suitability.',source:'https://www.blackmores.com.au/products/multivitamins-for-women'},
{id:'wagner-vitamin-c',name:'Vitamin C 1000 Chew',brand:'Wagner',category:'immunity',form:'Chewable tablets',size:'250 tablets',price:5950,oldPrice:6800,rating:4.7,reviews:39,stock:15,image:'/images/products/wagner-vitamin-c.webp',description:'A chewable vitamin C option for your daily routine. Read the manufacturer’s label for ingredients, directions and suitability.',source:'https://www.wagnerhealth.com.au/products/vitamin-c-1000-chew/'},
{id:'voost-multi',name:'Multivitamin Orange',brand:'VOOST',category:'daily-essentials',form:'Effervescent',size:'20 tablets',price:3250,rating:4.6,reviews:31,stock:22,badge:'A fresh routine',image:'/images/products/voost-multi.webp',description:'An effervescent multivitamin with an orange flavour. Check the label for serving information and the complete ingredient list.',source:'https://voostvitamins.com.au/products/effervescents/multivitamin'}
];
export const money=(n:number)=>'LKR '+new Intl.NumberFormat('en-LK',{maximumFractionDigits:0}).format(n);
export const getProduct=(id:string)=>products.find(p=>p.id===id);
export const districts=['Ampara','Anuradhapura','Badulla','Batticaloa','Colombo','Galle','Gampaha','Hambantota','Jaffna','Kalutara','Kandy','Kegalle','Kilinochchi','Kurunegala','Mannar','Matale','Matara','Monaragala','Mullaitivu','Nuwara Eliya','Polonnaruwa','Puttalam','Ratnapura','Trincomalee','Vavuniya'];
export type CartItem={productId:string;quantity:number};
export type Address={name:string;email:string;phone:string;address:string;city:string;district:string;postcode:string};
export type Order={id:string;created_at:string;items:{productId:string;name:string;price:number;quantity:number}[];subtotal:number;discount:number;delivery:number;total:number;address:Address;method:string;status:string};
export type StoreData={cart:CartItem[];wishlist:string[];recent:string[];orders:Order[];profile:Partial<Address>;user:{name:string;email:string}|null};
export const calculateTotals=(cart:CartItem[],coupon:string,delivery='standard')=>{const subtotal=cart.reduce((sum,item)=>sum+(getProduct(item.productId)?.price??0)*item.quantity,0);const discount=coupon.toUpperCase()==='WELL10'?Math.round(subtotal*.1):0;const shipping=cart.length?(delivery==='express'?850:subtotal-discount>=15000?0:450):0;return {subtotal,discount,delivery:shipping,total:subtotal-discount+shipping}};
