import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { CategoriesPage, ShopPage, BrandsPage, WishlistPage } from '@/components/globalmart/catalog-pages';
import { ProductPage } from '@/components/globalmart/product-page';
import { CartPage, CheckoutPage, AuthPage, AccountPage, OrdersPage } from '@/components/globalmart/checkout-pages';
import { AboutPage, ContactPage, LibraryPage, ArticlePage, InfoPage } from '@/components/globalmart/content-pages';
import { chatGPTSignInPath } from '@/app/chatgpt-auth';
import { getProduct, categories } from '@/lib/catalog';
export const dynamic='force-dynamic';
type Props={params:Promise<{slug:string[]}>;searchParams:Promise<Record<string,string|string[]|undefined>>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug=[]}=await params;let title=slug[0]?.replaceAll('-',' ')??'Wellness';if(slug[0]==='product')title=getProduct(slug[1])?.name??'Product';if(slug[0]==='category')title=categories.find(c=>c.id===slug[1])?.name??'Wellness';return {title:title.charAt(0).toUpperCase()+title.slice(1)+' | GlobalMart'};}
export default async function Page({params,searchParams}:Props){const{slug=[]}=await params;const query=await searchParams;const val=(k:string)=>typeof query[k]==='string'?query[k] as string:'';const first=slug[0];if(first==='product'&&slug.length===2){if(!getProduct(slug[1]))notFound();return <ProductPage key={slug[1]} id={slug[1]}/>;}if(first==='category'&&slug.length===2){if(!categories.some(c=>c.id===slug[1]))notFound();return <ShopPage key={slug[1]} category={slug[1]}/>;}if(first==='health-library'&&slug.length===2){if(!['read-the-label','your-daily-ritual','find-your-format'].includes(slug[1]))notFound();return <ArticlePage id={slug[1]}/>;}if(slug.length!==1)notFound();switch(first){case 'shop':return <ShopPage key={val('brand')} initialBrand={val('brand')}/>;case 'search':return <ShopPage key={val('q')} search initialQuery={val('q')}/>;case 'categories':return <CategoriesPage/>;case 'brands':return <BrandsPage/>;case 'offers':return <ShopPage offers/>;case 'wishlist':return <WishlistPage/>;case 'cart':return <CartPage/>;case 'checkout':return <CheckoutPage initialCoupon={val('coupon')}/>;case 'login':return <AuthPage signInHref={chatGPTSignInPath('/account')}/>;case 'register':return <AuthPage register signInHref={chatGPTSignInPath('/account')}/>;case 'account':return <AccountPage signInHref={chatGPTSignInPath('/account')}/>;case 'orders':return <OrdersPage/>;case 'about':return <AboutPage/>;case 'contact':return <ContactPage/>;case 'health-library':return <LibraryPage/>;case 'delivery':case 'faq':case 'privacy':return <InfoPage type={first}/>;default:notFound();}}
